[build]
  command = "npm run build"
  publish = "dist/public"

[build.environment]
  NODE_VERSION = "18"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  DATABASE_URL = "postgresql://neondb_owner:npg_7HfabeDdGUX8@ep-quiet-sunset-a54qddli.us-east-2.aws.neon.tech/neondb?sslmode=require"
  PGDATABASE = "neondb"
  PGPORT = "5432"
  PGHOST = "ep-quiet-sunset-a54qddli.us-east-2.aws.neon.tech"
  PGPASSWORD = "npg_7HfabeDdGUX8"
  PGUSER = "neondb_owner"